name: ci

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - uses: mydea/actions-ember-testing@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint:js
      - name: Run node tests
        run: yarn test:node
      - name: Run Ember tests
        run: yarn test:ember
